### ISSUE TITLE
DLL not found

### ISSUE THREAD

**Issue by CubikNeRubik** [skysoft-tech/cv-renderer#6]
App throw an error at start
```
Unhandled exception: System.TypeInitializationException: The type initializer for 'QuestPDF.Settings' threw an exception.
 ---> QuestPDF.Drawing.Exceptions.InitializationException: The QuestPDF library has encountered an issue while loading one of its dependencies. This type of error often occurs when the current runtime is missing necessary NuGet packages.

Please ensure the following NuGet packages are added to your project and has matching versions:
- SkiaSharp.NativeAssets.Win32
- HarfBuzzSharp.NativeAssets.Win32

For a detailed understanding, please examine the inner exception and consult the official SkiaSharp library documentation.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at SkiaSharp.SkiaApi.sk_typeface_ref_default()
   at SkiaSharp.SKTypeface..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKTypeface.get_Default()
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.CheckIfExceptionIsThrownWhenLoadingNativeDependencies()
   --- End of inner exception stack trace ---
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.Test()
   at QuestPDF.Settings..cctor()
   --- End of inner exception stack trace ---
   at QuestPDF.Settings.set_License(Nullable`1 value)
   at SkySoft.CvRenderer.Core.PdfRenderer.SetupLicense()
   at SkySoft.CvRenderer.Core.PdfRenderer.Render(Stream stream, CvOptions options)
   at SkySoft.CvRenderer.Cli.Executor.Run(String input, String output, Int32 width)
   at SkySoft.CvRenderer.Cli.Program.<>c.<<Main>b__0_1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by EugeneTitarchuk** [comment]
@CubikNeRubik Could you please verify that files
`libHarfBuzzSharp.dll`
`libSkiaSharp.dll`
are located in the same folder with `SkySoft.CvRenderer.Cli.exe`?

**Comment by CubikNeRubik** [comment]
I miss `libSkiaSharp.dll` during the file copy
now it works
